use rdev::Key;

pub fn parse_key(key_str: &str) -> Key {
    match key_str.to_uppercase().as_str() {
        "CONTROLLEFT" | "CTRL" | "LEFTCONTROL" => Key::ControlLeft,
        "CONTROLRIGHT" | "RIGHTCONTROL" => Key::ControlRight,
        "ALT" | "ALTLEFT" => Key::Alt,
        "ALTRIGHT" => Key::AltGr,
        "SHIFTLEFT" | "LEFTSHIFT" => Key::ShiftLeft,
        "SHIFTRIGHT" | "RIGHTSHIFT" => Key::ShiftRight,
        "BACKQUOTE" | "`" | "~" => Key::BackQuote,
        "SPACE" => Key::Space,
        "TAB" => Key::Tab,
        "CAPSLOCK" => Key::CapsLock,
        "A" => Key::KeyA,
        "B" => Key::KeyB,
        "C" => Key::KeyC,
        "D" => Key::KeyD,
        "E" => Key::KeyE,
        "F" => Key::KeyF,
        "G" => Key::KeyG,
        "H" => Key::KeyH,
        "I" => Key::KeyI,
        "J" => Key::KeyJ,
        "K" => Key::KeyK,
        "L" => Key::KeyL,
        "M" => Key::KeyM,
        "N" => Key::KeyN,
        "O" => Key::KeyO,
        "P" => Key::KeyP,
        "Q" => Key::KeyQ,
        "R" => Key::KeyR,
        "S" => Key::KeyS,
        "T" => Key::KeyT,
        "U" => Key::KeyU,
        "V" => Key::KeyV,
        "W" => Key::KeyW,
        "X" => Key::KeyX,
        "Y" => Key::KeyY,
        "Z" => Key::KeyZ,
        _ => Key::Unknown(0),
    }
}
